{% set name = "libmetgem" %}
{% set version = "0.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/metgem/libmetgem/archive/v{{ version }}.tar.gz
  sha256: b9b1a0868b07a435c67dd90fe32720b24cb4ed1f9d2f80e9e0d3d1b12bf82a49

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - pip
    - cython
    - numpy
    - scipy
    - versioneer
    - tomli          # [py<311]
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - {{ pin_compatible('scipy') }}
    - _openmp_mutex  # [linux]
    - llvm-openmp    # [osx]

test:
  imports:
    - libmetgem.cosine
    - libmetgem.database
    - libmetgem.filter
    - libmetgem.mgf
    - libmetgem.msp
    - libmetgem.neighbors
    - libmetgem.network
    - libmetgem._cosine
    - libmetgem._database
    - libmetgem._filter
    - libmetgem._mgf
    - libmetgem._msp
    - libmetgem._neighbors
    - libmetgem._network

about:
  home: https://github.com/metgem/libmetgem
  summary: 'A library for molecular networking based on MS/MS spectra.'
  license: GPL-3.0-only
  license_file: LICENSE
  doc_url: https://libmetgem.readthedocs.io
  dev_url: https://github.com/metgem/libmetgem

extra:
  recipe-maintainers:
    - n-elie
