{% set name = "libmetgem" %}
{% set version = "0.6.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/metgem/libmetgem/archive/v{{ version }}.tar.gz
  sha256: 60c42e5ae5754cac7f23f948380e8ae376bb4ad59a0b8b426b42e22be55a3c54

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - pip
    - cython
    - numpy
    - scipy
    - versioneer
    - toml
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - {{ pin_compatible('scipy') }}
    - _openmp_mutex  # [linux]

test:
  imports:
    - libmetgem.cosine
    - libmetgem.database
    - libmetgem.filter
    - libmetgem.mgf
    - libmetgem.msp
    - libmetgem.neighbors
    - libmetgem.network
    - libmetgem._cosine
    - libmetgem._database
    - libmetgem._filter
    - libmetgem._mgf
    - libmetgem._msp
    - libmetgem._neighbors
    - libmetgem._network

about:
  home: https://github.com/metgem/libmetgem
  summary: 'A library for molecular networking based on MS/MS spectra.'
  license: GPL-3.0-only
  license_file: LICENSE
  doc_url: https://libmetgem.readthedocs.io
  dev_url: https://github.com/metgem/libmetgem

extra:
  recipe-maintainers:
    - n-elie
